### ISSUE TITLE
Error when munki repo is not available

### ISSUE THREAD

**Issue by klou** [lindegroup/autopkgr#251]
Feature request:  If a munki repo is specified (or a *.munki.recipe is called), check if the munki repo is available and mounted.

Otherwise, the entire run fails with a long string of error messages (that also extend beyond the viewable pane).

**Comment by eahrold** [comment]
@klou what's your setup? Is your munki repo on a separate file server? It may be an even better feature to have AutoPkgr try to mount your munki repo.

**Comment by klou** [comment]
@eahrold Try to mount or check if it's mounted, either works.  If I recall, munkitools will mount the repo upon munkiimport if not immediately available.

I have munki (and others) being served by a CentOS VM, which has the repository mounted separately on a NAS.  Usually, I work directly on the repo itself (separate mounted volume).

**Comment by eahrold** [comment]
Since munkiimport will try to mount the share, I'm not sure of the reason for autopkgr to simply check whether it's mounted pre `autopkg run` because it shouldn't matter if it is or not. AutoPkgr has no direct control over things once it sets the run in motion. 

Actually having AutoPkgr mount the share may have some benefit in that it indicates if it can be successfully mounted.

If it's more an issue of the error message, I think autopkg itself is getting some updates to how exceptions hare handled which may produce more favorable results.

**Comment by klou** [comment]
Looks like there were 2 issues here, neither of which applies to AutoPkgr.
```
MUNKI_REPO=/Volumes/OSX-repo/munki_repo
Repo URL=smb://NAS.IP/OSX-repo/munki_repo
```
With the following, even `munkiimport` will fail to automount this share (as it needs to create the MUNKI_REPO path in line 136), due to the nested path.  Even changing the `os.mkdir` to `os.makedirs` won't fix this, as apparently creating nested paths in `/Volumes` is not a good idea.

Changing `MUNKI_REPO=/Volumes/munki_repo` in both the munkiimport.plist and autopkg.plist will fix this.  Leading to ...

The Autopkg MunkiImporter Processor by default assumes that MUNKI_REPO is already mounted (it calls `makepkginfo` and directly copies the resultant packages to MUNKI_REPO).  I can rip out the mount code  and checks from `munkiimport` and insert it into `MunkiImporter.py` and `MakeCatalogsProcessor.py`, and I'm relatively sure that it'll mount and dismount at the end of each run. 

But then, I think Greg might argue that it is adding unnecessary complications to Autopkg (and duplication of effort), as well as mounting/dismounting the same share EVERY time that a package is imported (which, I think is why he prompts whether or not the share should be dismounted after `munkiimport` is run).  That and in the case of `MakeCatalogsProcessor.py`, the mount code is practically longer than the processor itself (which really just calls `makecatalogs MUNKI_REPO`)

Which brings me back to the original request, I suppose.  Maybe a nice red/green light indicator under Folders & Integration > Munki Integration.  Obviously, adding a button to mount the share will require an additional Munki Repo URL input field.

If it helps, the mount code is here: https://github.com/munki/munki/blob/master/code/client/munkiimport#L97-L159

**Comment by eahrold** [comment]
Right, right, right, the MunkiImporter autopkg processor doesn't actually use munkiimporter it uses shutil.copy().

My hang up is that an indicator light won't really help when scheduled runs  are happening in the background. This is why I have more interest in addressing mounting the repo.

But I'm somewhat torn as to where it's appropriate to address this. On one hand handling in autopkg would probably be the most widely beneficial, but by handling in AutoPkgr we could address the problem in a very specific way and use native API's to do the mounting.

@klou thanks for bringing this up and for the spirited discussion, I'll do some more thinking about this, and if I come up with something I may have you give it a test drive.

--Eldon

**Comment by klou** [comment]
Well, I'm just going to leave this here (for purposes of discussion)

PROS of modifying the AutoPkg Processors:
* Automates one more step
* Adds some error checking
* No changes needed in AutoPkgr

CONS:
* Not everybody who uses AutoPkg uses Munki
* Will likely require another MUNKI_URL global variable (really, if so should pull from the munkiimport.plist, but I don't know if that's bad form)
* Will have to mount/dismount after every *.munki recipe run, unless it can be called at the beginning and end of the batch (scripted) run.  And that would require modifying more than the individual Processors.
* Error-checking for all of this.  

AutoPkg doesn't check for munkitools, it looks like.  (Which is a fair assumption, I suppose.)

**Comment by duel007** [comment]
Instead of having AutpPKgr mount the share if it's not there, why not have it simply check to see if the volume is available when starting the run, and if not then have a single error rather than running through each enabled recipe and giving an error for each one? I, like OP, host my munki repo elsewhere and sometimes it gets unmounted on the Mac that I run Autopkgr from.

**Comment by eahrold** [comment]
@duel007 the reason I would be a little reluctant to use that approach is there are potentially cases where it's not exclusively .munki recipes in the run.

**Comment by klou** [comment]
Updated for v1.3:  Nice work in checking for Munkitools.

When the external munki_repo is NOT mounted (but correctly configured), configuring munkitools Repo location defaults to a grayed-out ```/Users/Shared/Munki_repo```.  I recall whether or not this is the default...but having only a "Save and Exit" button to exit this screen scares me a bit.

Manually mounting the repo, and then repeating the process has the correct Repo location specified (in a non-grayed-out).  The previous "Save and Exit" didn't change my correct settings.

How about "Munki tools x.x.x is installed and Munki Repo is available" be the requirements for Green status?

**Comment by homebysix** [comment]
@klou That's a good point. I've been thinking separately that it would be nice to have [Cancel] and [Save]  as the options in all integration config sheets, rather than just [Save and Close].

Also, my original desire for the repo path to show up grayed-out if the path doesn't exist makes less sense now that we're taking repos on mounted sharepoints into consideration. We may want to go back to having the repo grayed-out only if `defaults read com.github.autopkg MUNKI_REPO` isn't set.

**Comment by eahrold** [comment]
Agreed. 
A third option is the text could be red if the path Isn't there.

**Comment by klou** [comment]
To be clear, my mounted repo is in ``//Volumes/.../munki_repo```, standard mounted sharepoints location.  I'm not sure where ```//Users/Shared/Munki Repo``` came from, unless you put that in as a suggestion or example.  If that's the case, then the grayed-out if MUNKI_REPO isn't set makes better sense.  Otherwise, confusion.

**Comment by homebysix** [comment]
@klou `/Users/Shared/munki_repo` is the path used in the Munki [demonstration tutorial](https://github.com/munki/munki/wiki/Demonstration-Setup), so we thought it was a sensible default.

@eahrold What about black text, but with a :warning: icon to the right. The icon could be clickable and show a message explaining that the path doesn't exist (perhaps because the repo's volume is not mounted). Would that work?
