### ISSUE TITLE
Feature request - Check if Casper-Admin is open / running

### ISSUE THREAD

**Issue by gerardweese** [lindegroup/autopkgr#253]
This more of an issue of managing Casper on the same machine you manage and run Autopkgr. The basic issue is if Casper Admin is logged in Autopkgr fails. It would be nice if Autopkgr just checked if CasperAdmin was in use.

**Comment by homebysix** [comment]
I think it's actually the presence of the mounted sharepoint that is the problem, and not Casper Admin itself. Maybe we could check for that instead.

**Comment by gerardweese** [comment]
Exactly.

**Comment by homebysix** [comment]
@eahrold Is this easy to implement, do you think?

**Comment by eahrold** [comment]
I was fooling around with this a little bit, but I'm not sure what the desired outcome is. 
If the check proves TRUE, what then?

Do we want to try to close Casper Admin, and unmounting the share? 
If that fails do we, un-stage the recipes, or continue on knowing an error will be produced. 

Isn't a generated error what we want after all, alerting us that something isn't working and needs to be addressed?

**Comment by homebysix** [comment]
I think we should abort all .jss recipes in the autopkg run and email an alert that says "Quit Casper Admin to continue running recipes with JSS integration."

Trying to close Casper Admin without knowing for sure what the app is doing is potentially hazardous. Best to simply report rather than take action.

**Comment by gerardweese** [comment]
@homebysix @eahrold I agree. This should just generate a useful error / warning nothing more.

**Comment by eahrold** [comment]
This may soon be moot. 
I think I figured out a way so CasperAdmin can be open while JSSImporter is processing.  The PR is here https://github.com/sheagcraig/python-jss/pull/28 if you want to check it out.

**Comment by eahrold** [comment]
@homebysix , @gerardweese 
Not sure if either of you are up to it, but it would be helpful if you could give the modification I have in the above PR a test drive.  You should be able to just switch out the  `/Library/Python/2.7/site-packages/python_jss-0.5.5-py2.7.egg/jss/distribution_points.py` for the one here https://github.com/eahrold/python-jss/blob/dynamic-mount-point/jss/distribution_points.py

On another note, I've been racking my head as to how to best address the issue of an open CasperAdmin, and it's rather difficult with how we currently use the `--recipe-list` argument in AutoPkgr's invocation since we can't easily filter out JSS recipes. Unless we move to an invocation that uses an array we'll probably just have to cancel the whole run if there are jss recipes and an open casper admin, otherwise we're basically where we are now with the subprocess error.

Then again maybe that's not too much of an issue, if you're running one jss recipe, they're probably all jss recipes right?

**Comment by eahrold** [comment]
New version of JSSImporter / python-jss takes care of this.

**Comment by homebysix** [comment]
Amazing!
