### ISSUE TITLE
Potential security issue using the Mac's serial number as the AutoPkgr.keychain password

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#271]
This would potentially allow somebody with physical access to the Mac to discover the SMTP password being used to send notifications from AutoPkgr. That SMTP password, in some organizations, may be linked to an important IT account, like the Google Apps administrator.

Might be worth thinking about alternative ways to set this password.

**Comment by eahrold** [comment]
I'm open to suggestions, the biggest problem is that in order to run AutoPkgr at the login window, the keychain needs to be unlocked and locked programmatically. 

Also keep in mind if users set their login keychain to `Lock after 5 minuets` we would need to pass the keychain password in or it would present an unlock dialog, causing AutoPkgr to hang completely until that password is entered.

The only reason we haven't seen this issue arise is that most users don't lock their login keychain password, but that's a separate security risk.

Since the keychain is in the users's library folder only the logged in user will have access to that file, a guest user wouldn't have access due to unix privileges.

I agree it's not ideal, but we're probably slightly better off than other solutions out there where the credentials are stored clear text in a script, and even JSSImporter stores credentials in defaults. 

Early on in the development of this feature, I was setting up the LaunchD to run autopkg as the root user, which does have access to the System keychain, which can be accessed without unlocking, but running the app in that context also had it's own set of issues. 

I think we could recommend setting up an e-mail account for AutoPkgr, 
but since the biggest security risk is limited to physical access and, if admins are at leasing setting a lock screen, require the login password too, I'm _fairly_ comfortable with how this is.

But as an alternative, we could improve the security somewhat if the keychain password were set somewhere privileged, and not world accessible, such as in the users home. Maybe generating a random key and saving it to a file like
`~/Library/Application Support/AutoPkgr/.keychainKey` 

I'd love to spitball more ideas with anyone security minded.

**Comment by eahrold** [comment]
A spitball branch up https://github.com/lindegroup/autopkgr/tree/v1.2.1-keychainKey that takes the above approach of using a .keychainKey file.

**Comment by eahrold** [comment]
@homebysix, @futureimperfect 

I think I may have figured this out!

Early on in development I wasn't having any luck creating a connection to the helper tool when the run was controlled by the launchd (particularly when at the login window).  That must have been before I realized that setting the `SessionCreate` key in the `com.lindegroup.AutoPkgr.schedule` launch daemon was required to get access to any keychain. 

Long story short, that key, it turns out will, also creates the necessary security session to allow connections to the helper tool. Which means we can now use the helper to read from the system keychain during background runs.

I also stumbled across this project https://github.com/google/santa with a much better code sign verification class `SNTCodesignChecker`, so I switched that in for AHCodesignVerifier. This really helped me lock down the helper application because it contained a method that can check the codesign of a binary based off a `pid_t` ( every NSXPCConnection has this @property ). Comparing that against the binary of the helper application for every connection means that if an application isn't signed with the Linde Group's certificate it's rejected right off the bat.

I would love if you both could give this branch a test drive https://github.com/lindegroup/autopkgr/tree/v1.2.1-systemKeychain I think this really locks things down in a much more ideal way.

**Comment by gregneagle** [comment]
If you are worried about disclosing an account password, storing it in the System keychain is _worse_ from a security perspective -- anybody with access to the machine and a logged-in account (or the credentials for any account) can read from the System keychain.

**Comment by eahrold** [comment]
@gregneagle, I'll be damned if you're not 100% correct. 

I was under the impression that it was limited to Admin access (not that that's great, but maybe better?), But I just tested it out with a standard account and sure as hell was able to get the password.

_here's how misleading it is_
![security prompt](https://cloud.githubusercontent.com/assets/3740088/6233470/a4bb3544-b698-11e4-8974-e425432ba770.png)

Strange thing is Keychain Access.app prompt seems to correctly require and admin user,  but when invoking with `security find-generic-password ...`, any user works. Regardless this approach needs scrapped!

I'm open to any suggestions / ideas. Would you vote for keeping with the `~/Library/Keychain/AutoPkgr.keychain` but using a keyFile to unlock the keychain item similar to how the system keychain uses the `/var/db/SystemKey`? I was initially heading in that direction with this branch [v1.2.1-keychainKey](https://github.com/lindegroup/autopkgr/blob/3b29872de7964d694df75b300132dcdf9a55f2f4/AutoPkgr/LGHostInfo.m#L117-L139)

We could even potentially secure that keyFile further by using the privilegedHelperTool to limit permissions to `-r--------    root   wheel`. 

Thanks for putting an eye on this, your help is greatly appreciated.

-- Eldon

**Comment by gregneagle** [comment]
Sorry --  I don't really have any great new ideas for you.

System.keychain needs admin/root access to _write_ to, but it's available for everyone to read from. That's the entire point! You put things in there that everyone needs access to -- CA certs, trust chains, wi-fi passwords, etc.

**Comment by eahrold** [comment]
I think that is the case for certificate items, but keychain password items are suppose to be slightly different.  

Anyone should be able to get a ref to item, but to actually retrieve the password data it should be limited to either the App that created it, (determined by either a matching code signature or the binary matching a checksum), or one listed as trusted app when creating the keychain item by adding an array of `SecTrustedApplicationRef` objects for the `kSecAttrAccess` key to the query when calling the `SecItemAdd()`. For example something like a wifi password only `AirPort` and `airportd` have unfettered access to that item.

so 
```
security find-generic-password -a myemail@pretendco.com -s "The KC item service" /Library/Keychains/System.keychain
```
simply returns the ref and attributes, but adding the -w key
```
security find-generic-password -a myemail@pretendco.com -s "The KC item service" -w /Library/Keychains/System.keychain
```
will prompt for access. 

I think it may be a bug because when accessing like this you _should_ be prompted to grant access to `security` binary, but it's definately not. 

But bug or not, taking this approach __is__ less secure, and thanks to your input we'll sensibly steer away.

**Comment by eahrold** [comment]
@homebysix, @futureimperfect 

Here's a wrap back around after @gregneagle  pointed out the flaw in using the System keychain...

https://github.com/lindegroup/autopkgr/tree/v1.2.1-keyFile-Keychain

It creates a keyFile for the keychain from random data, saves it to `/var/db/.AutoPkgrKeys/UID_xx`, then locks down both with `root 700` permissions. [(As seen Here)](https://github.com/lindegroup/autopkgr/blob/v1.2.1-keyFile-Keychain/helper/LGAutoPkgrHelper.m#L97-L155)

I've also included some keyFile reset methods, to handle situations where things break. Since only one item is stored in the keychain, wiping everything on error seems like a small price to pay to get back up and running. [(As seen here)](https://github.com/lindegroup/autopkgr/blob/v1.2.1-keyFile-Keychain/AutoPkgr/LGPasswords.m#L99-L122)

If you tested any of the other dev versions in this vein, you may need to uninstall/ reinstall the helper tool, since I didn't bump the helper tool's version.

Testing and feedback is appreciated.

Thanks,
Eldon
