### ISSUE TITLE
Overrides now listed in AutoPkgr

### ISSUE THREAD

**Issue by justinrummel** [lindegroup/autopkgr#277]
With the recent update to AutoPkgr, I now see my overrides being listed in the GUI, however, I'm not sure if I'm supposed to only check the local.jss.application, not check it, or check both. 

![screen shot 2015-02-15 at 1 30 10 pm](https://cloud.githubusercontent.com/assets/466605/6204381/15cb1480-b517-11e4-846e-cec3057f5556.png)

**Comment by eahrold** [comment]
If you want to run your override you check the `local.jss.AdobeFlashPlayer`, 
If you want to run the original recipe you check  `com.github.autopkg.jss.AdobeFlashPlayer`

And if you wanted to for some reason, you could run both.

**Comment by eahrold** [comment]
@justinrummel, I was actually just poking around a little bit more, and I suspect the recipe identifier `com.github.autopkg.jss.AdobeFlashPlayer` is actually from Allister Banks' jss repo not Shea Craig's. 

This is why you're seeing both. If you create an override with the same name as it's parent only one instance of `AdobeFlashPlayer.jss` is displayed. 

This is one of the main the reasons we switched to identifiers because so many seperate repos now have recipes with the same name.

Hope this clears it up a bit more.

Thanks,
Eldon

**Comment by eahrold** [comment]
@justinrummel,
Hey Justin did this answer your question?

Thanks,
Eldon

**Comment by justinrummel** [comment]
This helped.  Thanks!
