### ISSUE TITLE
Only e-mail when run from schedule. Post notification otherwise.

### ISSUE THREAD

**Issue by eahrold** [lindegroup/autopkgr#302]
Would it make sense to do it this way. If you're triggering the run manually I think a simple notification badge that when clicked opens a "report" popup window should suffice.

Votes?

**Comment by homebysix** [comment]
Actually, I think the existing behavior (email always) is better, because 1) it's more consistent, and 2) the first thing people often do to make sure AutoPkgr is working is to click the "Run AutoPkg Now" button and make sure the email came through.

In theory the Send Test Email button should do the job, but it's reassuring to know that all your selected recipes are being reported properly after the first run.
