### ISSUE TITLE
SMTP Server default port

### ISSUE THREAD

**Issue by jelockwood** [lindegroup/autopkgr#308]
As far as I can see AutoPkgr defaults to using/suggesting port 465 for contacting the SMTP server. While it is true that many mail servers support this port and it is also the case that Apple Mail as a client for example also suggests/tries that port it is my understanding that port 465 was never officially ratified as a port for SMTP traffic and is actually officially assigned to a different protocol. In other words port 465 is deprecated as far as use for SMTP traffic is concerned.

The more correct port to use instead should be port 587 which is also used by Apple Mail and far more mail servers.

I would therefore suggest that AutoPkgr should default to port 587 and as now there is always the option for administrators to change to 465 should they desire.

**Comment by homebysix** [comment]
Hi @jelockwood. The main reason I suggested using 465 was because it's the default port for smtp.gmail.com, which is the placeholder we use in the SMTP server field. Many of the companies that use AutoPkgr also use Google Apps to send mail, so this placeholder example is useful for many, I think.

However, we'll probably switch to a different interface for specifying ports soon. Something like this, perhaps:

![screen shot 2015-03-06 at 9 21 10 am](https://cloud.githubusercontent.com/assets/7801391/6530022/3ac01cf2-c3e2-11e4-83e9-c52ce3526747.png)
