### ISSUE TITLE
AWS Distribution Point

### ISSUE THREAD

**Issue by robbybarnes** [lindegroup/autopkgr#309]
Is there any way, or any plans for a way, to use an AWS distribution point?

It would be ideal if we could create an IAM user on AWS specifically for autopkgr and allow it to log in to our S3 storage with that individual IAM user, so that all logs are accurate and easy to determine where it is coming from.

**Comment by kitzy** [comment]
+1

**Comment by homebysix** [comment]
I'll have to defer to @sheagcraig since AutoPkgr rides along with JSSImporter w/r/t Casper integration. Shea, any idea how easy/hard this would be to implement?

**Comment by sheagcraig** [comment]
I suspect that they work exactly the same as a JDS. But I've never had access to one to test it. So the answer is that maybe it's really, really easy.

**Comment by robbybarnes** [comment]
You can set up a free account with S3 that gives you a decent amount of storage and IOs if it was something that someone wanted to test.  I know how to work with S3 and Amazon security stuff pretty well from a networking and storage/load balancing perspective, but I do not know much about coding or I'd offer to help out more.  If there's anything I could do to help with the development of this, I would be happy to.

**Comment by sheagcraig** [comment]
Cool. I wasn't really aware of that. I'll have to spin one up and see what I can find out. I'll let you know via this issue when I have something to test.

**Comment by homebysix** [comment]
Thanks Shea!

**Comment by sheagcraig** [comment]
So @robbybarnes I took a quick look at the Amazon stuff, and how to configure it in Casper. I've got a ton of projects in flux right now that I really need to keep working on, but you could do some investigation to help move this along.

First, I have an open issue on python re: CDP's, of which an AWS DP is one type sheagcraig/python-jss/issues/22. My request in that instance was to try setting up a CDP as a JDS and see what happens.

Here's my rationale (based on zero experience with the CDP type). The supported means for getting files onto your JDS is to use the web interface to upload files. However, you can also add them with Casper Admin, and then hit the "replicate" button to copy. And our packet dump of this process is how python-jss handles copying packages and scripts to a JDS.

Likewise, the web interface talks about how you have to hit "replicate" in Casper Admin to get files to sync to a cloud point, so I would imagine that it's actually the same process.

Indeed, it's sneaky. What *actually* happens when you "add a file to a JDS" is that a file gets posted to the _JSS_, which then handles the syncing to any JDS', and my guess is, also to AWS, etc. So the JDS DP type in python-jss just needs to know the address of your JSS, and the JSS uses the values in its database for the distribution points to distribute the files.

There's nothing really "type-specific" in the JDS code that would prevent it from also doing the CDP's, as far as I can tell.

So, specifics:
1. Try configuring a JDS and running a recipe through it.
2. If that doesn't work, I'd be interested in whether a JDS DP-type configured by hand and run from the commandline can do anything. This would take some know-how. I can probably assist with a very basic test-script, and you could just make sure the plist is set up correctly.
3. Barring those two, I would want to see a packet trace of what Casper Admin does when you add a package and replicate it to a system that has a configured CDP. This is potentially a pain in the butt because of having to have the keys to decrypt the SSL traffic. Almost certainly, this process is *still* just an HTTP POST. If we can recreate that POST, even with CURL (but preferably with python/requests), then it would be ready to start implementing.

Obviously any results you send in would have to be sanitized for security information!

**Comment by homebysix** [comment]
I think this is closely related to a discussion that's been happening on and off in the MacAdmins Slack channel. I think Shea is using Wireshark to reverse engineer how Casper Admin treats CDPs, and will probably end up changing JSSImporter's behavior to more closely match that. Until then, I don't think there's much we can add on the AutoPkgr end.

I'll keep this thread open here in case @sheagcraig needs anybody to test.

**Comment by homebysix** [comment]
Good news, this feature is due to find its way into 1.4 soon. Keep an eye on the releases page!

![screen shot 2015-12-04 at 1 50 47 pm](https://cloud.githubusercontent.com/assets/7801391/11602338/42c896bc-9a8e-11e5-987a-4a17ec7ce14e.png)

**Comment by homebysix** [comment]
AutoPkgr 1.4 is now available: https://github.com/lindegroup/autopkgr/releases/latest
