### ISSUE TITLE
Manually uninstalling JSSImporter causes AutoPkgr to think that AutoPkg isn't installed

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#327]
Steps to reproduce:

1. Remove folders starting with `python_jss` from /Library/Python/2.7/site-packages.
2. Launch AutoPkgr, notice that it thinks AutoPkg isn't installed.
3. Attempt to reinstall AutoPkg, but behavior remains the same.
4. Attempt to restart helper tool, but behavior remains the same.

**Comment by eahrold** [comment]
What's happening is removing python_jss like this actually causes AutoPkg (because of JSSImporter's now unmet dependencies) to crash. Running autopkg via the cli results in a traceback. 

Since the AutoPkg installer leaves JSSImporter in place reinstall of AutoPkg won't resolve the issue.

Reinstalling JSSImporter _will_ fix.

I'll see if I can come up with a sensible approach to solving this issue on our side, but it may be something that could be better addressed at the JSSImporter level.

**Comment by homebysix** [comment]
We discovered that removing `/Library/AutoPkg/autopkglib/JSSImporter.py` in addition to the above files seems to do the trick.

Would be nice to have an "Uninstall JSSImporter" option in AutoPkgr. Maybe holding Option on the Install tab turns everything to Uninstall? I'll think more on it.

In the meantime, you're right — having a sensible way to detect and report on situations like this would be better than the current behavior.

**Comment by everetteallen** [comment]
I continue to see this problem on a clean install of 10.10.3.  Everything works but AutoPKGR will not show that JSSImporter is installed.

**Comment by homebysix** [comment]
Hi @everetteallen — the original symptom I reported only occurs after trying to manually remove the /Library/Python/2.7/site-packages/python_jss* folders. Is that what you did?

If so, I recommend one of two options:
- If you want to continue using JSSImporter, reinstall it using the latest package [here](https://github.com/sheagcraig/JSSImporter/releases/latest).
- If you'd rather remove JSSImporter, manually remove the JSSImporter.py file I mention above.

We'll work on building in a more turnkey component uninstall system at some point. I'll open a feature enhancement request for that, and close this issue.
