### ISSUE TITLE
More granular and comprehensive uninstall options

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#332]
Looks like there are a few files that remain even after using the built-in Uninstall option in the AutoPkgr menu.

Can we give users the option of removing only the components they don't want, or removing everything at all? Something like this:

![screen shot 2015-04-17 at 2 05 17 pm](https://cloud.githubusercontent.com/assets/7801391/7210941/e26e0bc8-e50a-11e4-9e18-0fbf67e63c2f.png)

The effect of checking ALL these boxes and clicking uninstall should be to leave the Mac in a state that it was before Git, AutoPkg, AutoPkgr, and JSSImporter were installed at all.

I think _only the first option_ should be checked by default, but giving people the other options would speed up troubleshooting.

**Comment by homebysix** [comment]
Uninstallation of integrated components like JSSImporter is now possible in 1.3, but as far as I can tell the general AutoPkgr uninstallation process remains the same. I'd like to get to something like the above in a future version, so I'm leaving this open.

**Comment by eahrold** [comment]
Agreed. 
But wit a few caveats. 
- I definitely don't want to handle uninstalling Git. There's too many permutations.
- I'm a little nervous about handling uninstallation of AutoPkg itself since it has a multiple launchd's and items spread out across the FS.
    - I'm fine with purging preferences.
- I don't want to handle uninstalling Munki Tools for the same reasons as autopkg.

But I'm 100% in favor of selectable options as shown above.
