### ISSUE TITLE
"Error updating repo" message, [Try to repair settings] indicates fixed but it's not

### ISSUE THREAD

**Issue by fseesink** [lindegroup/autopkgr#354]
Around 8:40PM, I ran AutoPkgr and tried clicking on[Update Repos Now] as I sometimes do to see if there are any new repos, and I got a dialog box with an error message.  My options were to click on [Try to repair settings] or [OK].  As it wasn't clear what I should do, I simply selected [OK].  Now when I try clicking [Update Repos Now] I get this dialog box:
![screen shot 2015-05-12 at 8 58 02 pm](https://cloud.githubusercontent.com/assets/48991/7601818/a1dac22a-f8e9-11e4-8d0a-f84a24dc8a54.png)

If I now [Try to repair settings], I get this:
![screen shot 2015-05-12 at 8 59 17 pm](https://cloud.githubusercontent.com/assets/48991/7601830/cdf6663e-f8e9-11e4-923b-d57b8b406e48.png)

Ok, so things are fixed, right?  Nope.  Click on [Update Repos now], and we're right back at the previous dialog.  Rinse.  Repeat.

I'm not sure what I need to do here to fix this.  But the issue is completely reproducible and never occurred before.

Setup:
* Mac OS X 10.10.3 with all latest patches
* AutoPkgr 1.2.3

If anyone can help me I'd be grateful.  And if you need more info, do not hesitate to ask.

**Comment by homebysix** [comment]
Hi @fseesink — Have you manually modified any of the files in the RecipeRepos folder? Some people do that instead of creating a recipe override, but it's _not_ recommended and can lead to exactly the error you're seeing.

First, open Terminal and type `autopkg repo-update all`. You'll probably see at least one of them fail.

Then, return to AutoPkgr and uncheck/recheck the repo that failed to update. This will remove any changes you've made locally and re-download the repo from its source.

If that doesn't work, you may need to uncheck the repo in AutoPkgr, remove the folder from inside ~/Library/AutoPkg/RecipeRepos, then recheck the repo in AutoPkgr.

**Comment by fseesink** [comment]
homebysix, you are the king.  (Like the name by the way.)  That did fix it.

However, I did NOT modify any files in the particular repo.  Do repos sometimes become corrupted on their own?

When I ran the command via Terminal, this is the relevant portion of the output for the failed repo:
____
Attempting git pull for /Users/telcomm/Library/AutoPkg/RecipeRepos/com.github.autopkg.wardsparadox-recipes...
ERROR: Pull is not possible because you have unmerged files.
Please, fix them up in the work tree, and then use 'git add/rm <file>'
as appropriate to mark resolution and make a commit.
____

But at present I haven't used any of the apps listed under that repo, and unless I'm mistaken, I only recently added that repo.  (Forgot to check folder date before unchecking/rechecking.  Would be nice to have the repos both sorted alphabetically and listing when they were first added to AutoPkgr, but I'm just so grateful that this app exists at all.)

But thank you for your help.  I very much appreciate it.

**Comment by homebysix** [comment]
> Do repos sometimes become corrupted on their own?

That's a great question, and I'm not sure I can answer it yet. I've seen the same problem on my own Mac, even though I don't modify the original recipes. Since it's only happened to me once, and since it was easy enough to solve, I wrote it off as a one time glitch.

If it happens to you again (and especially if it happens in a way that unearths any kind of pattern), please re-open this one.

Good idea about the ability to sort repos. I'll open a separate issue for that.

**Comment by cattleman1** [comment]
homebysix, thank you for the fix.  It showed which Repo was messed up and all good again.  I appreciate you, my friend!
