### ISSUE TITLE
Quick Look recipes

### ISSUE THREAD

**Issue by MScottBlake** [lindegroup/autopkgr#370]
Right now, the only way to view a recipe is to create an override and then edit that. It would be nice if you could right click a recipe and inspect the code.

I understand the reason why it hasn't been added yet, since you want to discourage people from editing the recipe itself and force them to create overrides, but if we could load a read-only file in an editor, or even just a scrollable popup window I think it would help people when deciding between two seemingly identical recipes (AdobeFlashPlayer for example).

**Comment by eahrold** [comment]
@MScottBlake, thanks for the suggestion, we have also been thinking about this. We took it a slightly different approach and what we've got planned for 1.3 is to have a popover with the `autopkg info [recipe]` equivalent. Do you think that would be sufficient or is there an argument to be made for a full view of the recipe itself? 

![info-popover](https://cloud.githubusercontent.com/assets/3740088/8620558/dc100458-26e5-11e5-9020-c8a747c26b27.png)

**Comment by MScottBlake** [comment]
In my case, I'm looking at various jss recipes that have some extra metadata like category and such. There are many recipes that live in different repositories that are nearly identical, save for a couple options.

Using Category as an example, I know I could just pick one of the recipes and override it if necessary, but if another exists that better matches my existing categories, I'd prefer to do that than maintain an override.

Something like what you have there is good, but I think a view of all options being set would be great. It wouldn't necessarily need to be the xml recipe itself.

**Comment by eahrold** [comment]
That makes sense, but it'd probably would be best to just show the XML since it would be difficult to handle representing all of the potential processor arguments.  We easily add a `show xml` button on the info popover, or maybe just another contextual menu item for that open a NSTextView. Any preference there? 

@homebysix opinions?

**Comment by homebysix** [comment]
@MScottBlake I'm uneasy about providing an "open recipe in text editor" option for the reason @eahrold mentioned — it would encourage people to edit the recipes in the RecipeRepos folder instead of creating overrides.

Because we know that people make frequent trips to the ~/Library/AutoPkg folder, we put "Open in Finder" buttons here for the cache, repos, and overrides. That may get you close to where you want to be:
<img width="635" alt="screen shot 2015-07-12 at 8 20 20 am" src="https://cloud.githubusercontent.com/assets/7801391/8638393/fa0d35cc-286e-11e5-85f4-604ab5ff95d2.png">

Long term, maybe we could consider adding a "Reveal in Finder" option to the contextual menu when you right-click on a recipe. Would that be a good compromise between convenience for autopkg power users and protection for novice users?

**Comment by futureimperfect** [comment]
I like the idea of showing a read-only text view containing the recipe text. This could be a button in the popover or a contextual menu item. We could additionally provide a keyboard shortcut to display the text view. Thoughts?

**Comment by eahrold** [comment]
I was thinking earlier that we could possibly do a QuickLook triggered using the space bar.

**Comment by futureimperfect** [comment]
Exactly what I was thinking too, @eahrold.

**Comment by MScottBlake** [comment]
QuickLook style read-only view is pretty much exactly what I was thinking.

I wish I had thought to use the space bar though. (jealous)

**Comment by ryan8382** [comment]
I hope this is along the same topic. Is there any place to add something that says that there are over rides for the recipe? All of my overrides are a specific category, catalog or use FireFox ESR. I would like to see that added in.

**Comment by homebysix** [comment]
@ryan8382 That's actually a good point. We indicate in the Quick Look panel if the recipe has a parent recipe, but not a "child" recipe (including overrides). Do you think that would be useful? In what situation?

**Comment by eahrold** [comment]
@ryan8382 or are you suggesting that we highlight the "keys" that are being overridden?

**Comment by ryan8382** [comment]
I guess I would say both. From the recipe level it would be nice to see there is an override and maybe when you quicklook it would highlight what the override is/was. I also don't know if there is anyway to show what other options are possibly from the other recipes like catalog, category, or developer.

**Comment by homebysix** [comment]
@ryan8382 The idea sounds interesting, but I'm having trouble thinking of how it would be useful exactly. If I want to see which recipes are overridden, I look into the RecipeOverrides folder. As long as my overrides are named in a sane and logical way, it's pretty easy for me to tell. So, although it's a fun puzzle, I think I'm leaning towards no. Perhaps someday we can revisit it as part of a separate issue, if you have a compelling use-case.

@eahrold I think the final piece of @MScottBlake's original request is the ability to press the Space bar to toggle the recipe info panel, Quick Look style. Easy?

**Comment by ryan8382** [comment]
Could you just put an additional column in the recipe area that has a yellow dot or something if there is an override for a particular recipe?

**Comment by homebysix** [comment]
The yellow dot already means something else, so that would be confusing.

I think the farthest I'd want to go with that idea is inclusion of children/overrides in the recipe info panel:
![screen shot 2015-07-15 at 8 39 22 am](https://cloud.githubusercontent.com/assets/7801391/8702567/5a18cd86-2acd-11e5-9551-653ab36a5c8f.png)

**Comment by ryan8382** [comment]
Was that field there before? Sorry if it was. That can work. You can pick any other color for the column status if it gets added. I think it would be nice to see if there are overrides without having to do a quick look.

**Comment by homebysix** [comment]
The "Children/Overrides" field isn't there yet, but maybe someday it could be. What you see above is a masterful Photoshop job. ;-)

**Comment by homebysix** [comment]
The basic ability to get detailed recipe info is now built into 1.3.

For a future version, I propose that we add these two remaining things:
- Ability to see info by clicking a recipe and typing Space (like Quick Look)
- Information on children or override recipes, if they exist. (Since "children" is not an accepted autopkg term, maybe the field could be "Parent of:")

Keeping this open until those two things are finalized.

**Comment by homebysix** [comment]
Also see #473.
