### ISSUE TITLE
Error running recipes

### ISSUE THREAD

**Issue by ajh11g** [lindegroup/autopkgr#383]
Tried to run a few recipes today (most using JSS importer). I had just recently updated both JSS-Importer and AutoPkg, but receive an error when attempting to run any .jss recipe. The error I specifically get is:

"A Python exception occurred during the execution of autopkg, see the system log for more details.

[ERROR] Invalid version number '1.2.0rc2'.    "

Any ideas on how to fix that?

**Comment by homebysix** [comment]
Hi @ajh11g — could you try running the following command in Terminal, removing any confidential info from the output, and pasting back here with ``` above and below?
```
/usr/bin/python /usr/local/bin/autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist /tmp/autopkg-output.xml
```
If the error persists, chances are it's something other than AutoPkgr causing the problem.

**Comment by ajh11g** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1651, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1645, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1458, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 470, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 299, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 845, in main
    python_jss_version = StrictVersion(PYTHON_JSS_VERSION)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '1.2.0rc2'
```

**Comment by ajh11g** [comment]
It kinda looks like maybe an issue with my Python install.

**Comment by eahrold** [comment]
@sheagcraig, any idea why StrictVersion wouldn't be able to handle `1.2.0rc2` or why it would be getting that for a `python_jss_verson`?

**Comment by eahrold** [comment]
@ajh11g you may want to try re-installing the most recent JSSImporter, and if that doesn't work, install older versions and see if you have any luck rolling back.

https://github.com/sheagcraig/JSSImporter/releases

**Comment by ajh11g** [comment]
@eahrold That seems to be a good option, I've noticed the problem started happening after updating JSSImporter to version 0.4.1 . I'll report back with results if anything changes.

**Comment by ajh11g** [comment]
@eahrold Well I went all the way back to version 0.3.6 and was still receiving the same error.

**Comment by sheagcraig** [comment]
1.2.0rc2 is _not_ a strict version; that's why it's failing. I made the mistaken assumption that easy_install would not install a release candidate over a production version, but alas, I was wrong.

If you specifically install the old python_jss like this:
`sudo easy_install https://pypi.python.org/packages/2.7/p/python-jss/python_jss-1.1.0-py2.7.egg#md5=b24823281f0e0c6f7c8270f4e623af4a`
it should be happy again.

**Comment by eahrold** [comment]
That's what I suspected, but was finding a bunch of mixed messages as to what a "valid" strict version was, and this didn't help https://docs.python.org/2/distutils/apiref.html#module-distutils.version.

**Comment by ajh11g** [comment]
@sheagcraig Well I installed the old version, still no luck.

**Comment by sheagcraig** [comment]
@ajh11g With the same error?

If you replaced python-jss with the production version and then reinstalled JSSImporter, it will just upgrade python-jss again, resulting in the same error.

Alternately, you could quickly edit /Library/Python/2.7/site-packages/jss/__init.py__ so that the version just leaves off the rc2.

I guess I'll go ahead and "hide" that release so it stops installing for people, until I can read up on how easy_install chooses which package to install.

**Comment by ajh11g** [comment]
@sheagcraig That took care of it. I changed __version__ = "1.2.0rc2" to __version__ = "1.2.0" . Thanks for looking into this!
