### ISSUE TITLE
Recipe search results with spaces in name

### ISSUE THREAD

**Issue by pereljon** [lindegroup/autopkgr#410]
I'm not sure if this is only a display issue or also a functional issue, but when you *Search for a recipe on Github* and the search result has recipes with spaces in the name, the first word of the recipe shows up as the recipe name, and the second word shows up as the github repo name. See the "Comic/Life", "Final/Cut", "Logic/Pro", "Microsoft/Remote" and others in the attached image.
![screen shot 2015-07-31 at 10 40 46 am](https://cloud.githubusercontent.com/assets/1195913/9013421/ab437f26-3770-11e5-846f-9abcb5a4ca4a.png)

**Comment by homebysix** [comment]
Good catch. Looks like we're making an incorrect assumption that recipe names will not contain spaces. (Especially problematic now that the official [jss-recipes repo](https://github.com/autopkg/jss-recipes) encourages using spaces. Because it's 2015.)

@eahrold, it looks like `autopkg search` results always print the same number of spaces between columns. Perhaps we can use that to our advantage? See: https://github.com/autopkg/autopkg/blob/b5b856adbc05f746513404465fb33efebc67ee11/Code/autopkg#L803-L809

**Comment by eahrold** [comment]
Yep, I somewhat knew this was laying dormant. The problem is since we just have the output from `autopkg search ...` the only thing we can currently do is string parsing ( splitting on white space ). We could possibly check if the white space is > 1 but I don't think string parsing is a good approach to begin with and I'd rather remove as much of that as possible. Ultimately I see the fate of AutoPkgr search being a decoupling from AutoPkg and reimplementing it in AutoPkgr natively so we have the full JSON object to use.

**Comment by homebysix** [comment]
Queued up for 1.3.1.
