### ISSUE TITLE
Automatic parent recipe search feature not working

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#421]
When I run `autopkg run Caffeine.pkg` in Terminal, AutoPkg helpfully locates the repo that the missing parent recipe lives in:

```
Didn't find a recipe for com.github.keeleysam.recipes.Caffeine.download.
Search GitHub AutoPkg repos for a com.github.keeleysam.recipes.Caffeine.download recipe? [y/n]: y

Name                         Repo                  Path                                    
----                         ----                  ----                                    
Caffeine.pkg.recipe          homebysix-recipes     Caffeine/Caffeine.pkg.recipe            
Caffeine.download.recipe     keeleysam-recipes     Caffeine/Caffeine.download.recipe       
Caffeine.munki.recipe        keeleysam-recipes     Caffeine/Caffeine.munki.recipe          

To add a new recipe repo, use 'autopkg repo-add <repo name>'
Could not find parent recipe for Caffeine.pkg

Nothing downloaded, packaged or imported.
```

However, when I run this same recipe in AutoPkgr, it's less helpful. First, it correctly shows me this dialog box:
<img width="532" alt="screen shot 2015-08-10 at 5 59 29 am" src="https://cloud.githubusercontent.com/assets/7801391/9172005/09518dd6-3f25-11e5-8eab-c33edddc62f2.png">

But then, no matter whether I clicked "Yes" or "No," it says the following:
<img width="532" alt="screen shot 2015-08-10 at 6 05 04 am" src="https://cloud.githubusercontent.com/assets/7801391/9172102/d151272e-3f25-11e5-9e92-fbd9233ae3e9.png">

I think the expected behavior would be to have AutoPkgr open the search results page, as if I had searched for the parent recipe's identifier.
<img width="567" alt="screen shot 2015-08-10 at 6 00 56 am" src="https://cloud.githubusercontent.com/assets/7801391/9172059/5b8959f8-3f25-11e5-82cc-4e4a9dc210f4.png">

Or, if AutoPkgr is running in the background, skip the search and simply add an error to the notifications. (And perhaps remove the recipe with the missing parent from recipe_list.txt.)

**Comment by eahrold** [comment]
By design, autopkg itself won't "make suggestions" when run is invoked with  `recipe-list` so we're OK there.

I'm really not sure how to approach this. The biggest hurdle is how AutoPkg prints stdout, and what AutoPkgr can do with it. When AutoPkgr invokes `autopkg run` it sets up the data to get sent to the UI to display progress messages. On the other hand `autopkg search` collects all of the data and once the process is complete parses it into a dictionary.

To add to the difficulty, if the "Search Github AutoPkg repo for parent recipe" successfully found the recipe we would want to continue sending the stdout to the UI, but if it failed we would need to start collecting the subsequent strings in order to parse them out. Unfortunately AutoPkgr is only aware of the this state once the process has terminated, which is too late.

Right now I've got a PR open for AutoPkg https://github.com/autopkg/autopkg/pull/195 which in my testing is extremely good at finding parent recipes and may be the only real solution.

Until that point in time maybe we should just disable the feature altogether. We can just pipe `n\n` into the stdin when the interactive text is detected.

Thoughts?

**Comment by homebysix** [comment]
Agreed — Let's just pipe `n/n` into the stdin, like you said.
