### ISSUE TITLE
Allow autopkgr to check multiple repos at once

### ISSUE THREAD

**Issue by bp88** [lindegroup/autopkgr#434]
This is an enhancement request. Currently one must add one repo at a time. It would be great to be able to select all the repos you want and highlight them using a key like CMD (or SHIFT if all the repos are in sequential order) and then to be able to press spacebar to check/add all the selected repos.

Having to add one by one and waiting 3-4 seconds is a bit of a drag when initially setting up AutoPkgr or if you want to make multiple repo modifications in the future.

**Comment by homebysix** [comment]
@eahrold Today I learned that `autopkg repo-add repo1 repo2 repo3` works. Could we leverage that for this enhancement?

@bp88 I like your suggestion — command- or shift-clicking to multi-select the repos you want, then pressing the space bar to add them all. But that might conflict if we ever decide do use Quick Look for the repos list (as we plan to do for the recipes list). I wonder if a MunkiAdmin-like method might be better: Right-click the multiple repos, then Add Selected.

**Comment by homebysix** [comment]
Actually, I see that @avenjamin has already solved this problem, and perhaps in a better way. According to the comments [here](https://github.com/avenjamin/autopkgr/commit/e6f2f1679ae40b5114a4e974a786bed6dd2ca568), all repos will be selected/deselected if you hold Option while clicking on one. This is consistent with Apple's UI in at least one place I know of:

<img width="780" alt="screen shot 2015-08-21 at 7 44 00 pm" src="https://cloud.githubusercontent.com/assets/7801391/9422145/0f2bbcb0-483d-11e5-9217-91eb1cb58fbf.png">

I vote for this method in both the recipes and repos tables, if it's feasible to implement. I could certainly see why somebody might want to filter the recipes for a specific string and then add all the results.

**Comment by eahrold** [comment]
@homebysix I've been playing with this a little bit and while the above solution makes sense with recipes, but not so much with repos.

Basically it's all about what's filtered. For recipes you could filter by user name and recipe type (e.g. all `homebysix.munki` recipes) and that's helpful. But with repos most filters return all or one (filtering for `sam` returns two, but in that situation you're probably only looking for one or the other).

So with repos it makes the most sense to do it by hi-lighted rows and then via a contextual menu. 
The question then is, should recipes be handled the same for consistencies sake, or do you do it differently using the opt+click method for those?

**Comment by gjpalau** [comment]
Or simply add a checkbox that says Add All Repos...

**Comment by gjpalau** [comment]
@homebysix The reasoning behind that is that most of the time I end up clicking one by one to add all the repos, then I click the ones I don't want.  I don't understand why is it's not the right way to do AutoPkg, since everyone has their own way on how to use it given their different needs.  It is a real waste of time to go one by one to click them... Maybe it can be an item that you can turn on and off from the preferences but I don't see the harm in making it available like that.

Maybe you can explain what is the "right" way to do AutoPkg.

**Comment by poundbangbash** [comment]
Some applications you can hold the Option key down and click a box and it will select all of them.  Could that be implemented? 

I don't see adding multiple repos at once as being a common activity past the initial setup. Even then it's more a matter of finding what recipe you need and add the repo once that's found.  This is made easier now with the recipe search functionality built in to the app.

**Comment by eahrold** [comment]
@gjpalau I think the issue is that there needs to be an explicit trust for every repo you add. AutoPkg by it's nature makes this somewhat challenging. You need to hunt it down, and type it in.

AutoPkgr on the other hand makes this step easy. Conceptually `Enabling All` skirts the agreement.

That being said, what we have in the works now doesn't prevent you from adding all, you'll just need to select all of the rows then bring up the contextual menu.

![select-all](https://cloud.githubusercontent.com/assets/3740088/9535258/0fc7d7a6-4ce5-11e5-84ea-58b44160382e.png)

**Comment by eahrold** [comment]
@homebysix just pushed to https://github.com/lindegroup/autopkgr/commits/select-all branch.

Here's the breakdown
- Repos multiple can be enabled based on selected rows via contextual menu.

- Recipes can be enabled based on selected rows via contextual menu, or by option clicking to enable all displayed. Part of me is nervous about the option-click on recipes since it can potentially accidentally hose an entire recipe list. Who ever would like to weigh in on this should.

**Comment by homebysix** [comment]
@eahrold I hadn't actually thought of that, but it's a good point: option-clicking a check that's already enabled will disable all recipes. Let's leave the option-click out and only do the multi-select right-click.

**Comment by kitzy** [comment]
+1 for multi-select right click.

**Comment by eahrold** [comment]
@homebysix I just brought this up-to-date with 1.3.3-alpha. Are we still considering this?

**Comment by homebysix** [comment]
Yep, I think we settled on this:

- Use Command-click or Shift-click to select multiple recipes or repos, as per the usual OS X convention.
- Right-clicking on one of the recipes in a multiple selection reveals the following options:
    - Run Selected Recipes Only
    - Enable Selected Recipes
    - Disable Selected Recipes
- Right-clicking on one of the repos in a multiple selection reveals the following options:
    - Update Selected Repos
    - Add Selected Repos
    - Remove Selected Repos

Is that feasible?

**Comment by homebysix** [comment]
Separate feature request now exists for Quick Look on recipes list: #370
