### ISSUE TITLE
Two instances of AutoPkgr launch at login

### ISSUE THREAD

**Issue by homebysix** [lindegroup/autopkgr#439]
I've seen two instances of AutoPkgr launch at login on at least two Macs that I've installed it on. I don't have much more information than that at this point, but I'll add to this issue once I learn more.

Observed behavior:

- Two AutoPkgr menu icons appear.
- Two AutoPkg icons appear in dock (if the "Hide AutoPkgr in Dock" option isn't selected).
- Quitting one instance does not affect the other.

Expected behavior:

- Only one instance should run.

Steps to reproduce: TBD.

**Comment by ftiff** [comment]
+1
Had this issue when autoupdating to 1.3.1

**Comment by jmb03012** [comment]
ditto here, although its inconsistent as to when it happens.  note I had this with 1.3.1 beta 1 as well.

**Comment by oleary-bruce** [comment]
I also experienced this 2 or 3 times, but not in the four weeks.

Bruce

On Aug 31, 2015, at 6:04 PM, Elliot Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


I've seen two instances of AutoPkgr launch at login on at least two Macs that I've installed it on. I don't have much more information than that at this point, but I'll add to this issue once I learn more.

Observed behavior:

  *   Two AutoPkgr menu icons appear.
  *   Two AutoPkg icons appear in dock (if the "Hide AutoPkgr in Dock" option isn't selected).
  *   Quitting one instance does not affect the other.

Expected behavior:

  *   Only one instance should run.

Steps to reproduce: TBD.

**Comment by alwaysdns** [comment]
+1

**Comment by homebysix** [comment]
According to @alwaysdns, this is still happening in version 1.4 of AutoPkgr. I can't reproduce it myself.

**Comment by alwaysdns** [comment]
I think you can cancel this. Upon restart, it doesn’t seem to be happening. I did some System Preferences tweaking and I think it’s good. I’ll restart again later to be sure, but you can probably close this. Sorry for the panic.

**Comment by homebysix** [comment]
@ftiff @jmb03012 @oleary-bruce — Are any of you still experiencing this?

**Comment by ftiff** [comment]
Not for quite some time!

**Comment by jmb03012** [comment]
I have note seen that happen in quite some time.

reply@reply.github.com At: 03/16/16 17:48:38" data-digest="From: reply@reply.github.com At: 03/16/16 17:48:38" style="">
