### ISSUE TITLE
Known issue: AutoPkgr says Munki tools update available even though latest version is installed

### ISSUE THREAD

**Issue by sheagcraig** [lindegroup/autopkgr#493]
When trying to update an out-of-date munkitools, I get prompted for my creds, it appears to install, but then the indicator is still sad.

**Comment by homebysix** [comment]
I can vouch for this. Even after attempting to update and being prompted for my admin credentials, I'm stuck here:

<img width="536" alt="screen shot 2016-02-25 at 2 12 54 pm" src="https://cloud.githubusercontent.com/assets/7801391/13336247/ef36b9a2-dbc9-11e5-9290-69f15b87fadd.png">

**Comment by sheagcraig** [comment]
...and I can vouch for @homebysix. He's an American hero.

**Comment by eahrold** [comment]
That would make sense.
```
makecatalogs -V
2.5.1.2627
```

**Comment by eahrold** [comment]
Ok, so at least for the past few releases the remote v numbers have been limited to MAJOR.MINOR.PATCH, so I'm fine with moving to that. But I remember a while back having to go to 4 places to catch a hotfix, so I'm not sure what the best approach is. 

Votes?

**Comment by homebysix** [comment]
I think we should get some guidance from the Munki team on which version is the canonical one.

**Comment by gregneagle** [comment]
Versions are auto generated by the make_munki_pkg.sh script as part of the build. They are generated by counting the number of git revisions and generating a pseudo build number. This number can be different for each of the sub packages, depending on what might have been changed in each part of the code tree.

It appears the "meta" build number the script came up with is higher than the build numbers for the core and admin pkgs, leading to confusion. There's not much to be done about that for this release; perhaps when there is some time I (or someone else) can revisit the build script and understand this issue better, and see if there are ways to avoid this outcome in the future.

The canonical version for the munkitools is that returned by `sudo managedsoftwareupdate --version`.

One can also derive the same number by reading /usr/local/munki/munkilib/version.plist and concatenating the values of CFBundleShortVersionString and BuildNumber.

For "official releases", the intention is to always bump CFBundleShortVersionString. Interim builds may not increment that number; the BuildNumber would be the way to distinguish later development builds from an "official release".

**Comment by homebysix** [comment]
Thanks for weighing in @gregneagle.

So as far as AutoPkgr is concerned, I think this may be a decent solution:

- Add a checkbox to the "Configure Munki tools" options that says __Include development releases of Munki tools__. This box will be unchecked by default.
    ![screen shot 2016-02-25 at 4 20 52 pm](https://cloud.githubusercontent.com/assets/7801391/13339304/8d966702-dbdc-11e5-85f0-8067664d981a.png)
- When the box is unchecked, AutoPkgr will only notify when official releases are available. (e.g. 2.5.0 → 2.5.1)
- When the box is checked, AutoPkgr will also notify when development releases are available. (e.g. 2.5.1.2627 → 2.5.1.2630)

That way the default behavior will be sufficient for casual users and less likely to break, but the advanced behavior is still available to power users. @eahrold thoughts?

**Comment by gregneagle** [comment]
Or alternately: an "ignore this release; tell me when it changes again" option.

**Comment by homebysix** [comment]
Fortunately, we do already have that. Here's how it'll look in 1.4.
![screen shot 2016-02-26 at 8 51 29 am](https://cloud.githubusercontent.com/assets/7801391/13358850/2db2dd4a-dc66-11e5-963d-0dd394b25d6c.png)

**Comment by eahrold** [comment]
I think @gregneagle may be suggesting that that's the criteria we use to determine the newest version.  On successful install store the version indicated by the remote and then only say there's a new version when the remote changes its offering.

It's an interesting idea but may open up a different problem when the remote provides a patch for an older version, which will require a bit more logic to handle correctly.

**Comment by gregneagle** [comment]
This will continue to be a problem in the future for AutoPkgr, I fear. Take a look at https://munkibuilds.org/2.6.0.2668/

I've changed the package creation script so that in the future, the "overall" pkg version's final part will be the highest of the core, admin, app, launchd pkgs, so if that code had been in place the pkg would have been named "munkitools-2.6.0.2667.pkg", but the problem for _AutoPkgr_ would be the same:

`managedsoftwareupdate --version` would return 2.6.0.2665.

This is because the apps were modified more recently than the command line tools.

If a given release happens to have more recently modified command-line tools, then the overall pkg version will match; otherwise it may not.

It must be this way. let's say all the subpkgs were in sync for a release:

core: 2.6.0.2669
admin: 2.6.0.2669
app: 4.2.2669
launchd: 2.0.0.2669
And the the overall pkg is munkitools-2.6.0.2669.pkg

Now an important bug is fixed in Managed Software Center, but the command-line tools are unchanged:

core: 2.6.0.2669
admin: 2.6.0.2669
app: 4.2.2670
launchd: 2.0.0.2669
And the the overall pkg is munkitools-2.6.0.2670.pkg.

`managedsoftwareupdate --version` will still return 2.6.0.2669 as it is unchanged from the previous release.
"About Managed Software Center" will display "4.2.2670"; that version will also appear when you select the app in the Finder and choose File->Get Info.

**Comment by homebysix** [comment]
Given this...
> I've changed the package creation script so that in the future, the "overall" pkg version's final part will be the highest of the core, admin, app, launchd pkgs
...it seems clear to me that AutoPkgr should be doing the same — i.e. using the highest of the tools' versions, and comparing that to the GitHub release version.

**Comment by homebysix** [comment]
This seems to not be an issue with Munki 3.1, but I do still think it would be a nice improvement for AutoPkgr to compare the highest of the tools versions to the GitHub release version. Leaving this open.

**Comment by nathanperkins** [comment]
I'm having currently having this issue in AutoPkgr 1.4.2.

AutoPkgr reports that 3.2.1.3499 is available for update, even though I have installed the latest release of munkitools through AutoPkgr itself and via the pkg on github. I checked my version of Managed Software Center and it shows as 4.7.3499. When installing, I skipped the launchd component because I don't want the launchd running on this server.

The above workarounds for skipping a version of munkitools or including development releases do not show in my AutoPkgr options or I'm unsure where to find them.

![screen shot 2018-04-30 at 12 24 32 pm](https://user-images.githubusercontent.com/10337495/39445911-73bcce0e-4c71-11e8-896a-1df7da8a4ec7.png)

![screen shot 2018-04-30 at 12 25 13 pm](https://user-images.githubusercontent.com/10337495/39445933-8e2d1c30-4c71-11e8-9cc8-50a1e112d0f1.png)

```
$ managedsoftwareupdate -V
3.2.1.3498
$ munkiimport -V
3.2.1.3498
```

**Comment by homebysix** [comment]
This is a known issue. Details above, but TL;DR: Munki's release version on GitHub (which AutoPkgr uses to display the green/yellow indicator) does not always match the locally installed binary that AutoPkgr is checking against (I think it's `makecatalogs`).

You can safely ignore the yellow dot. Sorry for the inconvenience.

If anybody wants to take a shot at fixing the code, I'm guessing [here](https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Models/Integrations/LGMunkiIntegration.m#L96-L109) would be a good place to start.
