### ISSUE TITLE
Issue with Win Recipes that use 7zip

### ISSUE THREAD

**Issue by jgstew** [lindegroup/autopkgr#510]
**See here:** https://github.com/autopkg/hansen-m-recipes/issues/39

Apparently Win Recipes making use of 7zip work when run through the command line, but not the GUI.

**CC:** @patgmac & @hansen-m

**Comment by patgmac** [comment]
Are you guys able to shed any light on this? Can you duplicate the issue on your end?

**Comment by homebysix** [comment]
Could you give me one or two example recipes to try? I assume `com.github.hansen-m.download.FirefoxESR-Win` is one. Others?

**Comment by patgmac** [comment]
Non-ESR as well, com.github.hansen-m.download.googlechrome-Win and Win64, AdobeAIR-Win.download to name a few.

**Comment by hansen-m** [comment]
Also `com.github.hansen-m.download.googlechrome-Win64` and `com.github.hansen-m.download.googlechrome-Win`

Side note, the SharedProcessor BESRelevanceProvider is very similar except we are using the full path to the executable, but 7zip installations can be more ambiguous in where it gets installed.

**Comment by csteelatgburg** [comment]
No progress on this?

**Comment by homebysix** [comment]
Hi @csteelatgburg - No progress at this time. Check out the [development announcement](https://github.com/lindegroup/autopkgr/wiki/AutoPkgr----past,-present,-and-future) from a couple years ago, and please reach out if you're interested in contributing!

**Comment by mpanighetti** [comment]
Just spent some time hacking away at this issue, and I've figured out the root cause: AutoPkgr is using a `$PATH` definition that doesn't include `/usr/local/bin`, which is where Homebrew and other package managers install their binaries. As a result, any processor referencing a binary not stored in a path expected by AutoPkgr (which in my testing appears to be `/usr/bin:/bin:/usr/sbin:/sbin`) needs to have an absolute path defined, or it will fail to execute any commands using those binaries.

I would guess that the answer provided [here](https://github.com/autopkg/hansen-m-recipes/issues/39#issuecomment-196631584) would be relevant, that a fix on AutoPkgr's end would require changing NSTask behavior ([possibly here?](https://github.com/lindegroup/autopkgr/blob/3154df42f3705ea5c5c8639a9a03d80ae7295c6f/AutoPkgr/Models/Integrations/LGIntegration%20Base/LGIntegration.m#L599-L601)). But considering AutoPkgr's stalled development, I don't imagine that's forthcoming.

**Comment by shawnhonsberger** [comment]
Addressed via SharedProcessors changes to `autopkg:master`.
