### ISSUE TITLE
Send notifications if you click the ​*Run Recipes Now*​ button

### ISSUE THREAD

**Issue by bp88** [lindegroup/autopkgr#513]
This is an enhancement request. Based on a conversation with @homebysix on Slack, he mentioned the following:
https://macadmins.slack.com/archives/autopkg/p1458318195000642
> AutoPkgr will not send notifications if you click the ​*Run Recipes Now*​ button, because it assumes you're actively watching the progress and don't need notification.
> 
> However, it ​_will_​ send notifications if you choose ​*Run AutoPkg Now*​ from the menu item, since that runs in the background.

Can we NOT make that assumption and let it send an email notification if the "run recipes now" button is clicked?

**Comment by eahrold** [comment]
This is not the case.
It will send a notification when the button "Run Recipes Now"
The issue is actually probably related to incorrect handling of notifications we're hammering out for the next release.

https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Views-Controllers-XIB/Tab%20Views/LGRecipeReposViewController.m#L129-L142
