### ISSUE TITLE
Notify when recipe changes

### ISSUE THREAD

**Issue by llauren** [lindegroup/autopkgr#524]
The biggest security concern i have atm with software updates distribution automation is not that the updates are tainted, but the recipes that provide those updates may be. Yes, the latest Google Chrome is probably as kosher as the ten previous ones, but what if an update of the recipe points to a tainted Chrome?

Thus, i'd appreciate a notification with the diff of the recipe once it changes. In an ideal world, i'd like the opportunity to explicitly accept the changed recipe into production.

Thanks.

**Comment by homebysix** [comment]
Hi @llauren, I fully agree. In fact, I gave a talk on this topic at the MacAD conference in London a couple months ago. My notes are online, and you may be particularly interested in [this section](https://github.com/homebysix/macaduk2016#pay-attention-to-changes).

Taking your feature request quite literally, I can say that AutoPkgr does already notify you when _repositories_ need to be updated. That's what the yellow indicator in the repos table indicates:
![screen shot 2016-05-03 at 8 39 28 am](https://cloud.githubusercontent.com/assets/7801391/14988871/a5878e5a-110a-11e6-93db-b141fb7d04a2.png)

It's true that AutoPkgr doesn't notify you when _recipes_ need to be updated, because there's no concept in AutoPkg of updating recipes — only repos. I'd recommend right-clicking on the repos with the yellow indicator and choosing __Open GitHub Commits Page__ to see the latest changes.

In an ideal world, I'd love to see AutoPkgr gain the ability to drill down to individual recipe diffs prior to applying a repo update, taking into account which commit your local repo is currently at. Something like this:

1. Right-click on a repo and choose __Review Changes__.
2. You'd see a "diff" view of the available changes, perhaps something like this:
    ![autopkgr diff](https://cloud.githubusercontent.com/assets/7801391/14989598/77775ef2-110d-11e6-8f4a-7d0d312319d7.png)
3. You can choose to click __Apply Changes__ or simply __Close__ without changing anything. You could also choose to view the diff directly on GitHub.

That all looks and sounds nice, but I'm sure it's also a substantial amount of code required to make it happen. Any volunteers?

**Comment by aysiu** [comment]
Because of some of the recent AutoPkg mailing list discussions about security, I think this diff on individual recipes instead of whole repos needing updating is definitely the way to go. Obviously, it's a huge endeavor, and I don't think I have the coding skills to do any PRs on AutoPkgr, but I'd be more than happy to help with testing if this ever came to fruition.

**Comment by macmule** [comment]
Hi all,

I think with the v1 changes to trust info, this could be closed as AutoPKG core now warns if changed: https://github.com/autopkg/autopkg/wiki/Autopkg-and-recipe-parent-trust-info

Hope folks agree with my thinking on this

**Comment by homebysix** [comment]
That's a good call, I think. Thanks!
