### ISSUE TITLE
hidden recipes on recipe_list.txt not showing in GUI

### ISSUE THREAD

**Issue by klou** [lindegroup/autopkgr#551]
Using https://github.com/autopkg/hjuutilainen-recipes/blob/master/GitHub/Atom.munki.recipe as a  source, create an override.

Runs of this recipe via standard CLI runs my override.  However, with AutoPkgr, it runs both my override AND the original recipe so that the resultant Atom.dmg is imported twice.

Looking at my ~/Library/Application Support/AutoPkgr/recipe_list.txt, I have a handful of source recipes on the list that don't appear in the GUI.  Is there a better way to reconcile them?

**Comment by homebysix** [comment]
Hi @klou,

After you create an override for a particular recipe, AutoPkgr hides the original recipe from the list and only shows you the override. I think that was implemented with good intentions, but should probably be reverted so that AutoPkgr shows all recipes, override or not.

Until then, my recommendation is to make sure the recipe is _not_ checked when you create an override for it. Once the override is created, then check the override to include it in your scheduled runs.

Elliot

**Comment by klou** [comment]
Best of both worlds?  Hide the original if override is created and the original is not on the list?

**Comment by homebysix** [comment]
@klou For the sake of transparency, I'm leaning towards showing all recipes all the time.

**Comment by eahrold** [comment]
@homebysix AutoPkgr should still show both the original and override assuming you give the override a unique name, it will simply uncheck the original and check the override.

**Comment by homebysix** [comment]
@eahrold I think most people choose the default override name (which is not unique).

**Comment by eahrold** [comment]
@homebysix, I was just looking over this, and it's actually super simple to modify. We can just change `YES` to `NO` here. 

https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Models/AutoPkg%20Task/LGAutoPkgRecipe.m#L289

I think you're right. That behavior must have been a relic of when we were using the recipe names in the recipe_list.txt rather than the identifiers, so there's no need for it any more.

**Comment by homebysix** [comment]
I love when Obj-C changes are so simple that even I can do them. ;-)
