### ISSUE TITLE
Changing Template for AutoPkgr-created JSS Smart Groups and Policies

### ISSUE THREAD

**Issue by luisgiraldo** [lindegroup/autopkgr#564]
Question: is it possible to modify the template names that are used by AutoPkgr when creating Smart Groups and Policies in JSS?

**Comment by homebysix** [comment]
Yes, you can use a custom SmartGroupTemplate.xml or PolicyTemplate.xml file to create policies and groups with any name you like. You can see an example of this [here](https://github.com/homebysix/auto-update-magic/blob/master/Exercise5b/PolicyTemplate-autoupdate.xml#L3) — the policy name has been changed to say "Auto Update Foo" instead of the default "Install Latest Foo."

You can also change the file names of the templates themselves. Name the .xml file whatever you like, but make sure of two things:

1. The JSS recipe (or recipe override) must refer to the correct file name in the GROUP_TEMPLATE and/or POLICY_TEMPLATE variables. ([Example](https://github.com/homebysix/auto-update-magic/blob/master/Exercise5b/Firefox-autoupdate.jss.recipe#L12).)
2. The file must exist in one of the folders in your AutoPkg search path. I usually put my templates in ~/Library/AutoPkg/Recipes or ~/Library/AutoPkg/RecipeOverrides along with the recipes themselves.

For more details, check out the [JSSImporter](https://github.com/sheagcraig/JSSImporter) readme and the [Auto Update Magic](https://github.com/homebysix/auto-update-magic) readme. They're lengthy, but they give examples of template overrides.
