### ISSUE TITLE
A Python exception occurred

### ISSUE THREAD

**Issue by edmlab** [lindegroup/autopkgr#565]
I just returned to my office after being away for two weeks and noticed that AutoPkr has not downloaded updates since Oct 7th. I tried running Recipes manually and I received the following response. 

"A Python exception occurred during the execution of autopkg, see the system log for more details.
[ERROR] UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 204: ordinal not in range(128)"

I haven't a clue as to why this is happening or how to fix it. 
Can someone please help. 

Thanks

**Comment by homebysix** [comment]
Hi @edmlab,

A few other people have reported the same error in the last week. It's usually because of a badly formatted recipe or override in your AutoPkg search directories.

Question: Do you have the tallfunnyjew-recipes repository checked in AutoPkgr? During my testing, I encountered a similar error that should be fixed when [this PR](https://github.com/autopkg/tallfunnyjew-recipes/pull/7/files) gets merged.

Also see [previous issues](https://github.com/lindegroup/autopkgr/search?q=%22codec+can%27t+encode%22&type=Issues&utf8=%E2%9C%93).

**Comment by edmlab** [comment]
Hello Elliot, Thank you for the reply. I have removed some of the search directories including  “tallfunnyjew-recipes” 

the problem seems to have resolved.

Thank you
 
Michael Conrader
CLT  EDM LAB
City College of New York
CG120
212.650.7095
631,839.2463
mconrader@ccny.cuny.edu

**Comment by homebysix** [comment]
Thank you. That confirms my hunch.
