### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by jfuchtm** [lindegroup/autopkgr#578]
Can you point me in the right direct on this error, it just started coming up today.

[ERROR] : 'ascii' codec can't encode character u'\u2019' in position 190: ordinal not in range(128)

AutoPkg 1.0.1
Git 2.5.4
AutoPkgr 1.4.2
LANrevImporter 0.5.4

Thanks

**Comment by homebysix** [comment]
Hi @jfuchtm,

There's no shortage of [similar issues](https://github.com/lindegroup/autopkgr/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22can%27t%20encode%20character%22). Generally, I've found the root cause to be a malformed or unfinished recipe in your AutoPkg search path.

Try running your recipes from Terminal and see if the error persists:

```
/usr/bin/python /usr/local/bin/autopkg run --verbose --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt
```

If so, you may see which recipe(s) are triggering the error.
