### ISSUE TITLE
Oracle Java 8 JDK.jss triggers an email alert on every run.

### ISSUE THREAD

**Issue by chilcote** [lindegroup/autopkgr#584]
Running the Oracle Java 8 JDK.jss recipe in AutoPkgr results in an email alert:
New software was downloaded:
NAME	VERSION
Oracle Java 8 JDK	1.8.0

AutoPkgr is not parsing the %version% from the parent recipe correctly (https://github.com/autopkg/novaksam-recipes/blob/d29e6f9fefbc6ef08a32da1d9c6d7287da4cfc8f/Recipes%20-%20pkg/OracleJava8JDK.pkg.recipe)

Steps to reproduce:
1. Choose the Oracle Java 8 JDK.jss recipe in AutoPkgr, and run it.
2. Review the email report.
3. Run the same recipe again.
4. Review the email report.

Expected behavior:
There should not be an alert in the email report that "New software was downloaded." 

Actual behavior:
On every run, AutoPkgr thinks that there is a new version of JavaJDK to report.

System:
MacOS 10.12.2, AutoPkgr 1.4.2

**Comment by homebysix** [comment]
Hi @chilcote —

I actually see two issues here. I think I know the solution to the first one, but not the second.

First, the fact that the recipe is triggering alerts to be sent on every run. I think this is normal, depending on how you have your notification triggers configured. Here's why:

When you run most recipes, the URLDownloader processor saves metadata about the download (etag, last-modified, and/or file size). On subsequent runs, the file is only downloaded if the file has changed. For example, here's a snippet from my first AdobeFlashPlayer.pkg run:

```
$ autopkg run -v AdobeFlashPlayer.pkg
Processing AdobeFlashPlayer.pkg...
...
URLDownloader: Storing new Last-Modified header: Tue, 10 Jan 2017 04:28:23 GMT
URLDownloader: Storing new ETag header: "1212589-545b5ea2f885e"
URLDownloader: Downloaded /Users/elliot/Library/AutoPkg/Cache/com.github.autopkg.pkg.FlashPlayerExtractPackage/downloads/AdobeFlashPlayer.dmg
...
```

And here's a snippet from the next run:

```
$ autopkg run -v AdobeFlashPlayer.pkg
...
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/elliot/Library/AutoPkg/Cache/com.github.autopkg.pkg.FlashPlayerExtractPackage/downloads/AdobeFlashPlayer.dmg
...
```

Now let's compare that to what we see when we run the Java JDK recipe. Here's the first run:

```
$ autopkg run -v OracleJava8JDK.pkg.recipe
...
URLDownloader: Storing new Last-Modified header: Wed, 14 Dec 2016 19:41:25 GMT
URLDownloader: Storing new ETag header: "053951fc1fa47569ff42a99d147cfa07:1482266261"
URLDownloader: Downloaded /Users/elliot/Library/AutoPkg/Cache/com.github.novaksam.pkg.OracleJava8JDK/downloads/Oracle Java 8 JDK.dmg
...
```

And here's the next run:

```
$ autopkg run -v OracleJava8JDK.pkg.recipe
...
URLDownloader: Storing new Last-Modified header: Wed, 14 Dec 2016 19:41:25 GMT
URLDownloader: Storing new ETag header: "053951fc1fa47569ff42a99d147cfa07:1482266261"
URLDownloader: Downloaded /Users/elliot/Library/AutoPkg/Cache/com.github.novaksam.pkg.OracleJava8JDK/downloads/Oracle Java 8 JDK.dmg
...
```

It downloaded the dmg again from scratch, even though the etag and last-modified is unchanged. Why? I can't say with certainty, but I'm guessing it's because of the [additional Cookie request header](https://github.com/autopkg/hansen-m-recipes/blob/master/Oracle/OracleJava8JDK.download.recipe#L42-L46) required to accept the license agreement. In any case, the `download_changed` environment variable is being set to `True` which causes the "new items were downloaded" message to appear in the summary results.

```
{'Output': {'download_changed': True,
            'etag': '"053951fc1fa47569ff42a99d147cfa07:1482266261"',
            'last_modified': 'Wed, 14 Dec 2016 19:41:25 GMT',
            'pathname': u'/Users/elliot/Library/AutoPkg/Cache/com.github.novaksam.pkg.OracleJava8JDK/downloads/Oracle Java 8 JDK.dmg',
            'url_downloader_summary_result': {'data': {'download_path': u'/Users/elliot/Library/AutoPkg/Cache/com.github.novaksam.pkg.OracleJava8JDK/downloads/Oracle Java 8 JDK.dmg'},
                                              'summary_text': 'The following new items were downloaded:'}}}
```

This might be worth opening an issue on hansen-m-recipes, since that's where the download recipe lives. But the fact that the software is being downloaded every run explains why you're getting those notifications repeatedly.

There is a way to prevent downloaded software from triggering notifications to be sent, using AutoPkgr's "Choose which actions trigger notification" settings. However, in your case it might not help, because the JDK recipe actually uses PkgCopier and JSSImporter too.

![screen shot 2017-01-18 at 12 18 16 pm](https://cloud.githubusercontent.com/assets/7801391/22081388/41d15018-dd78-11e6-95eb-39b229bb54ad.png)

In other words, in order to mute the JDK notifications, you'd have to turn off ALL the useful triggers, which is kind of useless. So your best bet is to see if hansen-m can find a way to prevent downloading the file if the version is unchanged.

Phew... OK, on to the second issue:

AutoPkgr is not displaying the correct version number in its notifications. The email displays "1.8.0" when it should be displaying "1.8.0_121". A `version` environment variable is present, so AutoPkgr should have no need to parse the filename of the copied package.

I'm going to have to dig into this when I get some troubleshooting time, but the good news: it's a cosmetic notification issue, rather than something that would cause policies/smart groups to be created incorrectly.

Thanks for reporting! I'll keep you posted.

**Comment by chilcote** [comment]
Great response, thanks Elliot.

I tried with the notification triggers turned off, and indeed you are right, sir. I'll see if I can figure it out, but it's not that big of a deal overall; I mean, besides, at least this way I know it's running daily, right? :)

Let's just keep this ticket open for the second part.  Let me know if you want me to try anything.

**Comment by homebysix** [comment]
I'd be willing to bet that second part is related to this issue: https://github.com/lindegroup/autopkgr/issues/307

Not sure it's going to get fixed, TBH.
