### ISSUE TITLE
AutoPkgr does not upgrade Munki tools

### ISSUE THREAD

**Issue by llauren** [lindegroup/autopkgr#595]
I get nightly email notifications that Munki tools 3.0.1.3344 is now available. Yet, the Install page on the AutoPkgr app is happy with Munki tools 3.0.0.3333 installed (greyed out <kbd>Install Munki tools</kbd> button, green light).

The version numbers are for illustration only, this has happened before with previous versions.

Workaround: Quit the app (<kbd>⌘ Q</kbd>, `Quit AutoPkgr` from the luggage menu won't help) and start it again.

**Comment by homebysix** [comment]
Interesting — it's likely that the "Install" tab is not refreshing automatically after helper tool update checks.

Curious whether the issue persists if you do the following:

1. Switch to the Repos & Recipes tab.
2. Add or update a repo.
3. Switch back to the Install tab.
4. Observe whether the Munki tools indicator is now yellow.

Or the following:

1. Open AutoPkgr, but close the main window to let the app run "headless."
2. Leave it in this state overnight, so you receive a Munki tools update email notification.
3. Click the AutoPkgr icon in the dock to bring up the main window.
4. Switch to the Install tab.
5. Observe whether the Munki tools indicator is now yellow.

It's understandable to expect the Install tab to refresh to show available updates, and I don't remember noticing otherwise in the past. However, I usually run AutoPkgr "headless" so I may have inadvertently prevented myself from encountering what you encountered.

**Comment by thomasm2film** [comment]
Since munkitools-3.0.2.3348 was out today, AutoPkgr will announce an update for this (Munki tools 3.02.3348 update now available) - but the "Update Munki Tools" button will not successfully be able to update this. It's still orange after the update. I tried manually updating munkitools with same results. Thanks for this awesome tool!

**Comment by fkick** [comment]
There's a version discrepancy inside the current release of Munki tools. This has been driving me crazy for the past week :)

See
https://github.com/munki/munki/issues/789

**Comment by rfitzwater** [comment]
I am having this issue with Munki tools 3.2.1.3499.  I updated Munki tools and Autopkgr is still listing them as outdated (yellow dot).  Quitting tool, reinstalling munki, etc. does not fix the issue.

**Comment by walkintom** [comment]
+1 - also having a reoccurrence of this issue with the Munki Tools 3.2.1.3499 update.

**Comment by oleary-bruce** [comment]
On Apr 26, 2018, at 5:13 AM, Tom Case <notifications@github.com<mailto:notifications@github.com>> wrote:


+1 - also having a reoccurrence of this issue with the Munki Tools 3.2.1.3499 update.

I'm also experiencing this problem, but haven’t been very concerned about it.

Bruce

**Comment by Tafkaroll** [comment]
+1 - also having a reoccurrence of this issue with the Munki Tools 3.2.1.3499 update

**Comment by homebysix** [comment]
This is a known issue, detailed here: 
https://github.com/lindegroup/autopkgr/issues/493
