### ISSUE TITLE
[Log] Updating MunkiTools & Generic Trust Issue Error

### ISSUE THREAD

**Issue by ta-itpanther** [lindegroup/autopkgr#597]
Hi all - quick backstory: I have a rudimentary understanding of code and (amazingly) with much research, got MunkiAdmin and AutoPkgr to work pretty fantastically for a bit. It wasn't too long ago that once I had to update MunkiTools, that I was getting errors on that and a trust issue with SketchUpMake. I do get that common error and it already is set with an Override. I do just get a common trust failure issue with no explanation as to what caused it.  As far as MunkiTools, well.. I have a log with both issues in PDF format.

I apologize for my ignorance but I figure to go directly to the source. Thanks!

[ta_autopkgr.pdf](https://github.com/lindegroup/autopkgr/files/1131189/ta_autopkgr.pdf)

**Comment by homebysix** [comment]
Hi @ta-itpanther,

All the recipes you're running appear to be overrides, as indicated by their identifiers in the log:

```
AutoPkgr Processing local.munki.Skype...
```

However the SketchUp Make recipe appears to be the one from dataJAR rather than your own override. That might explain why the SketchUp recipe is producing a trust error:

```
Processing com.github.dataJAR-recipes.munki.SketchUp Make 2017 EN...
```

As for your MunkiTools error, I don't see any instance of MunkiTools in the log you provided, so I'm not sure what that could be.

**Comment by homebysix** [comment]
Closing this, but do reply if you have more information. Thanks.
