### ISSUE TITLE
Feature request (Automated Version Priority)

### ISSUE THREAD

**Issue by vendettarwb** [lindegroup/autopkgr#599]
Automated Version Priority

Situation, you just snagged a sweet .pkg from a repo, edited the override file, tested and then pushed a package out into the wild, your boss comes along and says wouldn't "add on to .pkg be great!?" requests the exact package that you just issued, only +1 smaller detail to add to your override. Hrumph

Looking for a way to bump the priority of the new package early without having to take it apart, re version and repackage, ATM I move the package into composer, create source (manually fix permissions as it seems to kill permissions), Change version number/Change source info, repackage and upload into munki repo. Would love to just be able to add something in the override that would change this, or be able to set a variable.

This very well could be learning opportunity for myself if there is an easier way :) If there was something in the walk throughs I missed, my apologies in advance.

**Comment by homebysix** [comment]
Hi @vendettarwb — I'm having trouble envisioning what "smaller detail" would require repackaging. Couldn't you remove the item from your Munki repo and AutoPkg cache, modify the override as necessary, and then run the override to re-import again with the correct settings?

**Comment by vendettarwb** [comment]
Thanks so much for getting back to me :)
Like if my Boss asks me to add one more module in Munkireport and half the org has already got the file I pushed out, its tested it works fine but now he wants more, so I have to edit the override file, I did the steps you outlined in your answer, my questions is why do we have to manually do this (I know it is how it works) I just mean humans are not good at repetition computers are :) This is not a criticism as well I am just wonder if there has been any talk of automating this?

**Comment by homebysix** [comment]
**General answer**: This will vary from recipe to recipe, and thus would be very difficult to add a "feature" that would work reliably with the multitude of different recipes out there. Plus, it's not a common use case as far as I've heard.

**MunkiReport-specific answer**: When first deploying MunkiReport, I ran into this exact issue. If I remember correctly, I added an `install_check` script or `installs` array  to the initial version that looked for the existence of the new modules, and installed if they weren't present. When MunkiReport subsequently received a version update, that tweak was no longer necessary.

This isn't the sort of thing I'd want to try to automate, since it's only likely to happen the first time a new piece of software is deployed. The "version" Munki cares about should normally be the software version itself, not the iteration of the IT admin's preferences within that version.
