### ISSUE TITLE
all recipes are failing

### ISSUE THREAD

**Issue by lkraft** [lindegroup/autopkgr#600]
getting the error:  is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding... for all of the recipes 

have tried creating an override, which also failed
![screen shot 2017-07-25 at 7 35 51 am](https://user-images.githubusercontent.com/16673224/28577662-4181190e-710c-11e7-9299-52f9a99d235f.png)

also tried running repos in terminal, also failed w/ the same trust error.

please advise
thanks!

**Comment by homebysix** [comment]
Hi @lkraft! If the recipes are also failing in Terminal, then AutoPkgr isn't involved. You may want to jump on macadmins.org Slack and join the #autopkg room.

Off the top of my head, it looks like you're experiencing [this issue](https://github.com/autopkg/autopkg/issues/355), which has been fixed by the AutoPkg developers and will be included in the next version of AutoPkg.

**Comment by lkraft** [comment]
thanks ell!!  hope you're well!
