### ISSUE TITLE
AutoPkgr does not like autopkg 2.0.1 RC1

### ISSUE THREAD

**Issue by jby** [lindegroup/autopkgr#635]
When running a scheduled run of my list of recipes:
```
-   File &quot;/usr/local/bin/autopkg&quot;, line 126
   log_err(f&quot;WARNING: plist error for {filename}: {err}&quot;)
 ^
SyntaxError: invalid syntax
```

Apparently re-produced by @homebysix when trying to add the autopkg/recipes repo as well...

Tried:
```plutil -lint ~/Library/AutoPkg/RecipeOverrides/*.recipe```
And:
```find ~/Library/AutoPkg -iname "*.recipe" -exec plutil -lint "{}" '+'```

Both report all "OK"

**Comment by homebysix** [comment]
Here's the screenshot I took after trying to add the autopkg/recipes repo:
![image](https://user-images.githubusercontent.com/7801391/72787460-d0ce8880-3be4-11ea-8af0-e38a72a099fd.png)

I highly suspect this is due to AutoPkgr explicitly calling /usr/bin/python (macOS built-in Python 2) for interpreting autopkg tasks, which will fail since autopkg 2.0 requires Python 3.
- https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Models/AutoPkg%20Task/LGAutoPkgTask.m#L321
- https://github.com/lindegroup/autopkgr/blob/master/AutoPkgr/Models/AutoPkg%20Task/LGAutoPkgTask.m#L1355

Any potential fix would need to work with both AutoPkg 1.x (usually running Python 2 from /usr/bin/python) and AutoPkg 2.x (which will run Python 3 from /usr/local/autopkg/python, which is a symlink to the actual Python 3 binary stored elsewhere). Maybe something like "use /usr/local/autopkg/python if it exists, else use /usr/bin/python."

**Comment by shawnhonsberger** [comment]
Thanks, @homebysix. Yes, @jby please use AutoPkg 1.4.1 with AutoPkgr in the meantime.

**Comment by shawnhonsberger** [comment]
@jby AutoPkgr 1.5.2 is out now. Please give this release a shot and let me know how it goes. Thanks! https://github.com/lindegroup/autopkgr/releases/tag/v1.5.2

**Comment by jby** [comment]
Installing and testing now

**Comment by jby** [comment]
One thing noticed immediately: AutoPkgr 1.5.2 does **not** offer to upgrade AutoPkg from 1.4.1 to 2.0.1 at startup - as 1.5.1 did...
Running my recipe-list now, will report back when done.

**Comment by shawnhonsberger** [comment]
Thanks! Please note that AutoPkg 2.0.1 is still pre-release. AutoPkgr does not prompt users to update AutoPkg until it is the full release version.

**Comment by shawnhonsberger** [comment]
Closing for now, please feel free to re-open if it re-occurs.
