### ISSUE TITLE
Error running recipes - Could not find parent recipe

### ISSUE THREAD

**Issue by sikosis** [lindegroup/autopkgr#693]
Does autopkgr actually work? I added the repo and got a green dot -- run a recipe and it can't find ANY of the recipes I select.

So, either the product doesn't work or it's producing an incorrect error dialog.

<img width="1101" alt="Screen Shot 2022-09-28 at 10 19 53 am" src="https://user-images.githubusercontent.com/1312559/192659958-91431f02-9557-4d02-ac42-300ab814de21.png">

**Comment by shawnhonsberger** [comment]
Hi @sikosis. Yes, I can tell you definitively that AutoPkgr does work. It is telling you that you do not have the parent repos added for the recipes that you are actually trying to use. In order to run these recipes, you would first need to add the grahampugh-recipes and jss-recipes repos. You can accomplish what you need with Jamf by installing the JamfUploader integration.

I should note when working with Jamf that it is no longer recommended to use .jss recipes (as JSSImporter is now deprecated) and you should use .jamf JamfUploader recipes instead. It is also recommended to create overrides of recipes before running them in your environment. Please take some time to familiarize yourself with the [Wiki](https://github.com/lindegroup/autopkgr/wiki), especially the following sections:

- https://github.com/lindegroup/autopkgr/wiki/Managing-Parent-Repos
- https://github.com/lindegroup/autopkgr/wiki/Overrides-and-Trust-Info
- https://github.com/lindegroup/autopkgr/wiki/Jamf-Pro

Also, please check out the @jamf-upload channel on the MacAdmins Slack. Thanks, and good luck! :)
