### ISSUE TITLE
Recipe overrides disappear from recipe list

### ISSUE THREAD

**Issue by PaRkThEcAr** [lindegroup/autopkgr#701]
So I created some overwrites based on the Firefox-Patch.jamf recipe from the garaham-recipes repository. However they don’t seem to show up in Autopkgr even when placed in the RecipeOverrides folder

**Comment by shawnhonsberger** [comment]
Thanks @PaRkThEcAr. Is the recipe a .yaml recipe, or have a .yaml dependency? AutoPkgr does not support YAML recipes or recipes with YAML dependencies at this time. Here's some context from the [release notes](https://github.com/lindegroup/autopkgr/releases):
Due to the fact that there is no native YAML library for macOS, AutoPkgr does not support `.yaml` recipes and they will not display in the recipe list. However, AutoPkgr will be able to run any recipe you like via your recipe list (even if those recipes are `.yaml` and are added to your recipe list manually, or have parent recipes that are `.yaml`). AutoPkgr's recipe list is stored at `~/Library/Application Support/AutoPkgr/recipe_list.txt` and can be edited with any text editor.
