### ISSUE TITLE
Autopkgr not working with macOS Sonoma

### ISSUE THREAD

**Issue by mak-cs** [lindegroup/autopkgr#704]
After opening Autopkgr 1.6 under macOS Sonoma 14.1.1, only an empty window is displayed. This behavior is the same for Apple Intel and Apple Silicon devices. Am I doing something wrong?

Best regards
MAK-CS

**Comment by shawnhonsberger** [comment]
Hi @mak-cs, thanks. Per the Release Notes in the [Changed](https://github.com/lindegroup/autopkgr/releases/tag/v1.6) section:
Due to the fact that macOS no longer ships with Python, you will now need to install [AutoPkg](https://github.com/autopkg/autopkg/releases) first on new Macs _before_ installing AutoPkgr. This gives AutoPkgr the path to Python it needs to run smoothly. If you already have AutoPkg installed, you already have the built in Python that ships with AutoPkg and can just install AutoPkgr.
