### ISSUE TITLE
Option to send local notifications instead or in addition of emails

### ISSUE THREAD

**Issue by scriptingosx** [lindegroup/autopkgr#79]
While the option of sending emails is certainly useful I would also like to have a local feedback on the screen. Could you add local notifications if an update is available?

**Comment by homebysix** [comment]
@eahrold I think 1.3 is set to use OS X notifications for several things, but not for alerting of updates to AutoPkg, Munki Tools, JSSImporter, etc. Would that be possible? Then we could close this out.

Ideally the update notification would be "sticky" like an App Store update:
![updates-available-mavericks](https://cloud.githubusercontent.com/assets/7801391/8690616/b086c68a-2a6b-11e5-9efc-86a21adfd172.jpg)
...but even a transient notification is better than no notification.

**Comment by eahrold** [comment]
This is trickier than it seems. 
You can make it sticky by changing the setting in System Preferences to alert. 

We can supposedly make notifications AutoPkgr posts default to alert style by setting a key in the plist, but I can't quite get that to work because I suspect that once you manually change it, the info.plist setting won't override that choice.

**Comment by homebysix** [comment]
Yeah, that's what I thought — stickiness determined per-app, not per-alert. Since we don't want all AutoPkgr notifications to be sticky, let's leave it as non-sticky.

But let's do make sure we throw up a notification when tools updates are available.

**Comment by homebysix** [comment]
Took us a year, but I think we can close this one. :-)
